name: BladeBooks
favicon: null
layout_spectrum: 0.4190785198006779
typography_spectrum: 0.6628294717520475
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9461685044225305
  lightness: 0.4942619639914483
  saturation: 0.6472200159914792
  rhythmicContrast: 0.7303438370581716
purpose: []
